/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Complejo;
import javax.swing.JOptionPane;

/**
 *
 * @author jaime
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Complejo c;

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtImaginaria1 = new javax.swing.JTextField();
        txtReal1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbOperaciones = new javax.swing.JComboBox<>();
        txtReal2 = new javax.swing.JTextField();
        txtImaginaria2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtReal3 = new javax.swing.JTextField();
        txtImaginaria3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("OPERACIONES CON NUMEROS COMPLEJOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos:"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtImaginaria1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImaginaria1KeyTyped(evt);
            }
        });
        jPanel2.add(txtImaginaria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 40, 30));

        txtReal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReal1ActionPerformed(evt);
            }
        });
        txtReal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReal1KeyTyped(evt);
            }
        });
        jPanel2.add(txtReal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("i");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 10, 40));

        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicacion", "Dividir" }));
        jPanel2.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 70, -1));

        txtReal2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReal2KeyTyped(evt);
            }
        });
        jPanel2.add(txtReal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 40, 30));

        txtImaginaria2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImaginaria2KeyTyped(evt);
            }
        });
        jPanel2.add(txtImaginaria2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("i");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 10, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 360, 100));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resultado:"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtReal3.setEditable(false);
        jPanel3.add(txtReal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 30));

        txtImaginaria3.setEditable(false);
        jPanel3.add(txtImaginaria3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 40, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("i");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 20, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 100));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 110, 30));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(406, 322));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtReal1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReal1KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtReal1KeyTyped

    private void txtImaginaria1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImaginaria1KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtImaginaria1KeyTyped

    private void txtReal2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReal2KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtReal2KeyTyped

    private void txtImaginaria2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImaginaria2KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtImaginaria2KeyTyped

    private void txtReal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReal1ActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed

        if (txtReal1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite por favor la parte real");
            txtReal1.requestFocusInWindow();
        } else if (txtImaginaria1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite por favor la parte imaginaria");
            txtImaginaria1.requestFocusInWindow();
        } else if (txtReal2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite por favor la parte real");
            txtReal2.requestFocusInWindow();
        } else if (txtImaginaria2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite por favor la parte imaginaria");
            txtImaginaria2.requestFocusInWindow();
        }
        try{
            
        
        int real1 = Integer.parseInt(txtReal1.getText());
        int imaginario1 = Integer.parseInt(txtImaginaria1.getText());

        Complejo c1 = new Complejo(real1, imaginario1);

        int real2 = Integer.parseInt(txtReal2.getText());
        int imaginario2 = Integer.parseInt(txtImaginaria2.getText());

        Complejo c2 = new Complejo(real2, imaginario2);
        Complejo f3;
        int op = cmbOperaciones.getSelectedIndex();

        switch (op) {
            case 0:
                f3 = c1.Sumar(c2);
                txtReal3.setText("" + f3.getReal());
                txtImaginaria3.setText("" + f3.getImaginario());
                break;
            case 1:
                f3 = c1.Resta(c2);
                txtReal3.setText("" + f3.getReal());
                txtImaginaria3.setText("" + f3.getImaginario());
                break;
            case 2:
                f3 = c1.Multiplicacion(c2);
                txtReal3.setText("" + f3.getReal());
                txtImaginaria3.setText("" + f3.getImaginario());
                break;
            case 3:
                f3 = c1.Dividir(c2);
                txtReal3.setText("" + f3.getReal());
                txtImaginaria3.setText("" + f3.getImaginario());
                break;                
        }
        cmdCalcular.setEnabled(false);
        txtImaginaria1.setEnabled(false);
        txtImaginaria2.setEnabled(false);
        txtImaginaria3.setEnabled(false);
        txtReal1.setEnabled(false);
        txtReal2.setEnabled(false);
        txtReal3.setEnabled(false);
        cmbOperaciones.setEnabled(false);
        }catch (NumberFormatException e){}

    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtReal1.requestFocusInWindow();
        txtReal1.setText("");
        txtReal2.setText("");
        txtReal3.setText("");
        txtImaginaria1.setText("");
        txtImaginaria2.setText("");
        txtImaginaria3.setText("");

        cmbOperaciones.setSelectedIndex(0);
        cmdCalcular.setEnabled(true);
        txtImaginaria1.setEnabled(true);
        txtImaginaria2.setEnabled(true);
        txtImaginaria3.setEnabled(true);
        txtReal1.setEnabled(true);
        txtReal2.setEnabled(true);
        txtReal3.setEnabled(true);
        cmbOperaciones.setEnabled(true);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperaciones;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtImaginaria1;
    private javax.swing.JTextField txtImaginaria2;
    private javax.swing.JTextField txtImaginaria3;
    private javax.swing.JTextField txtReal1;
    private javax.swing.JTextField txtReal2;
    private javax.swing.JTextField txtReal3;
    // End of variables declaration//GEN-END:variables
}
